//AddWatchWindowVars.js
expRemoveAll
expAdd ("PSFB_gui_icommand_Set_Amps", getNatural())
expAdd ("PSFB_icommand_Set_pu", getNatural())
expAdd ("Cmpss1Regs.RAMPMAXREFS.RAMPMAXREF", getNatural())
expAdd ("PSFB_gui_ocpThreshold_Amps", getNatural())
expAdd ("PSFB_gui_ovpThreshold_Volts", getNatural())
expAdd ("PSFB_closeGiLoop", getNatural())
expAdd ("PSFB_closeGvLoop", getNatural())
expAdd ("PSFB_guiIHV_Amps", getNatural())
expAdd ("PSFB_guiLVbus_Volts", getNatural())
expAdd ("PSFB_ovp_Fault", getNatural())
expAdd ("PSFB_ocp_Fault", getNatural())
expAdd ("Cmpss1Regs.COMPDACCTL.RAMPSOURCE", getNatural())
expAdd ("PSFB_slope", getNatural())
expAdd ("PSFB_guivLVBus_Set_Volts", getNatural())
expAdd ("PSFB_guivLVBus_SlewedSet_Volts", getNatural())
expAdd ("PSFB_start_flag", getNatural())
expAdd ("EPwm1Regs.DBRED.DBRED", getNatural())
expAdd ("EPwm1Regs.DBFED.DBFED", getNatural())
expAdd ("EPwm2Regs.DBRED.DBRED", getNatural())
expAdd ("EPwm2Regs.DBFED.DBFED", getNatural())
expAdd ("EPwm4Regs.DBRED.DBRED", getNatural())
expAdd ("EPwm4Regs.DBFED.DBFED", getNatural())
expAdd ("PSFB_cntlMax", getNatural())
expAdd ("PSFB_cntlMin", getNatural())